### ISSUE TITLE
how do you fix settings for nucleus looking like this and i'm on latest version 

### ISSUE THREAD

**Issue by Cxsmo-ai** [steviegt6/nucleus#14]
how do you fix settings for nucleus looking like this and i'm on latest version 
![image](https://user-images.githubusercontent.com/74084396/208283092-c8dba2d2-7bb8-4a69-bb2d-0a079f82e931.png)

**Comment by steviegt6** [comment]
Probably fixed in 72023baff7e69f3da27a77b5c84545ac78bf4bf9, core issue needs further reconsideration.
