### ISSUE TITLE
Acrylic Window Dragging is Buggy/Laggy

### ISSUE THREAD

**Issue by steviegt6** [steviegt6/nucleus#2]
The config pop-up's frame is visible until a fullscreened window is brought to the front. Dragging acrylic windows is noticeably laggy.

**Comment by HerXayah** [comment]
Try going into latest Vibe version maybe that fixes it
FYI i compiled latest Vibe here if u cant/want do it urself
https://github.com/PrincessAkira/OpenAsar/blob/main/src/vibe.node

**Comment by steviegt6** [comment]
I had figured this was an issue on my side (I also haven't tested on my newest computer) but I'll check this out later today - thanks!

**Comment by HerXayah** [comment]
I have discovered the Acrylic doesnt even work at all for me .-.

**Comment by steviegt6** [comment]
The one packaged with nucleus? Make sure you're installing the correct archive.

**Comment by HerXayah** [comment]
> The one packaged with nucleus? Make sure you're installing the correct archive.

I am.
Im also facing bugged options as in #14

**Comment by steviegt6** [comment]
Your options issue is probably actually related to #16. I'll look into all of this later, thanks!

Though if your settings menu is facing issues, surely that means that you were unable to actually test using vibe? It's off by default.

**Comment by steviegt6** [comment]
Oh, this is... new.

![image](https://user-images.githubusercontent.com/27323911/216481211-49fa898a-65dc-4e18-a3a3-f85f7f9f8b61.png)

**Comment by steviegt6** [comment]
@PrincessAkira, very late, but I've made the setting menu not abysmal. I'll have a look at acrylic windows now...

**Comment by steviegt6** [comment]
Works fine for me, though I'm still facing the actual problem this issue describes.

**Comment by steviegt6** [comment]
I have made the executive decision to just not bother with support, https://github.com/uwu/Acrylic does it better and we already support shelter.

**Comment by HerXayah** [comment]
I discovered a somewhat Fix kinda.
If you disable Performance Mode it does work for me a bit

**Comment by steviegt6** [comment]
Noted.
